eight_points_guzzle:
    clients:
        jenkins_client:
            base_url: '%akeneo_ci.api.url%'

            options:
                auth:
                    - ahocquard
                    - ooo
