eight_points_guzzle:
    clients:
        jenkins_client:
            base_url: '%env(resolve:JENKINS_API_URL)%'
            options:
                auth:
                    - '%env(resolve:GITHUB_USER)%'
                    - '%env(resolve:GITHUB_TOKEN)%'
