version: '1.0'

services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: akeneo_ci_metrics
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - '3306:3306'
      networks:
        - akeneo

    mysql-test:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: akeneo_ci_metrics
      ports:
        - '3307:3306'
      networks:
        - akeneo-test

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        networks:
          - akeneo

volumes:
    mysql: ~

networks:
    akeneo: ~
    akeneo-test: ~
