parameters:
    env(JENKINS_API_URL): ''
    env(GITHUB_USER): ''
    env(GITHUB_TOKEN): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\Delivery\CLI\ImportRunMetricsCommand:
        arguments:
            $pipelineNames:
                - 'pim-community-dev'
                - 'pim-enterprise-dev'

    App\Infrastructure\Delivery\CLI\ImportTestMetricsCommand:
        arguments:
            $pipelineNames:
                - 'pim-community-dev'
                - 'pim-enterprise-dev'

    GuzzleHttp\ClientInterface: '@eight_points_guzzle.client.jenkins_client'
